routes/dashboard_route.py
import datetime
import os

from flask import (
    Blueprint,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename

from constant import BASE_DIR
from database import db_handler
from models.invite import Invite
from models.page_title import build_title
from models.user import User

dashboard_bp = Blueprint("dashboard", __name__)

UPLOAD_FOLDER = os.path.join(BASE_DIR, "uploads")


@dashboard_bp.route("/set_password", methods=["POST"])
@login_required
def set_password():
    user = current_user
    filename = request.form.get("filename")
    new_password = request.form.get("new_password")
    if not filename:
        return jsonify({"error": "Filename and password are required"}), 400

    password_hash = generate_password_hash(new_password) if new_password else None
    db_handler.execute(
        "UPDATE uploads SET password_hash = ? WHERE filename = ? AND owner_identifier = ?",
        (password_hash, filename, user.account_identifier),
    )
    return jsonify({"success": "Password set successfully"}), 200


@dashboard_bp.route("/delete_file", methods=["POST"])
@login_required
def delete_file():
    user = current_user
    filename = request.form.get("filename")
    if not filename:
        session["notification"] = {"message": "No filename provided", "type": "error"}
        return jsonify({"error": "No filename provided"}), 400

    filename = secure_filename(filename)
    file_path = os.path.join(UPLOAD_FOLDER, filename)

    if not os.path.exists(os.path.abspath(UPLOAD_FOLDER)):
        session["notification"] = {"message": "Invalid file path", "type": "error"}
        return jsonify({"error": "Invalid file path"}), 400

    if os.path.exists(file_path):
        os.remove(file_path)
        db_handler.execute(
            "DELETE FROM uploads WHERE filename = ? AND owner_identifier = ?",
            (filename, user.account_identifier),
        )
        session["notification"] = {
            "message": "File deleted successfully",
            "type": "success",
        }
        return jsonify({"success": "File deleted successfully"}), 200
    session["notification"] = {"message": "File not found", "type": "error"}
    return jsonify({"error": "File not found"}), 404


@dashboard_bp.route("/clear_notification", methods=["GET"])
def clear_notification():
    session.pop("notification", None)
    return "", 204


@dashboard_bp.route("/")
@login_required
def dashboard():
    user = current_user
    uploaded_files_count = db_handler.execute(
        "SELECT COUNT(*) FROM uploads WHERE owner_identifier = ?",
        (user.account_identifier,),
    )[0][0]
    views_count = (
        db_handler.execute(
            "SELECT SUM(views) FROM uploads WHERE owner_identifier = ?",
            (user.account_identifier,),
        )[0][0]
        or 0
    )
    storage_usage = (
        db_handler.execute(
            "SELECT SUM(size) FROM uploads WHERE owner_identifier = ?",
            (user.account_identifier,),
        )[0][0]
        or 0
    )
    storage_usage = f"{storage_usage / (1024 ** 3):.2f} GB"

    recent_uploads = db_handler.execute(
        "SELECT original_name, filename, upload_time, size FROM uploads WHERE owner_identifier = ? ORDER BY upload_time DESC LIMIT 10",
        (user.account_identifier,),
    )

    formatted_uploads = []
    for upload in recent_uploads:
        upload_time = datetime.datetime.strptime(upload[2], "%Y-%m-%d %H:%M:%S.%f")
        formatted_upload_time = upload_time.strftime("%Y-%m-%d %H:%M")
        formatted_uploads.append(
            (upload[0], upload[1], formatted_upload_time, upload[3])
        )

    return render_template(
        "dashboard_home.html",
        active_page="home",
        pagetitle=build_title("Dashboard"),
        username=user.username,
        uploaded_files_count=uploaded_files_count,
        views_count=views_count,
        storage_usage=storage_usage,
        recent_uploads=formatted_uploads,
        is_admin=user.is_admin,
    )


@dashboard_bp.route("/settings", methods=["GET", "POST"])
@login_required
def settings():
    user = current_user
    if request.method == "POST":
        try:
            if "update_email" in request.form:
                new_email = request.form["email"]
                password = request.form["password"]
                if user.check_password(password):
                    user.email = new_email
                    user.save()
                    flash("Email updated successfully.", "success")
                else:
                    flash("Incorrect password.", "error")
            elif "update_username" in request.form:
                new_username = request.form["username"]
                password = request.form["password"]
                if user.check_password(password):
                    user.username = new_username
                    user.save()
                    flash("Username updated successfully.", "success")
                else:
                    flash("Incorrect password.", "error")
            elif "update_password" in request.form:
                current_password = request.form["current_password"]
                new_password = request.form["new_password"]
                confirm_new_password = request.form["confirm_new_password"]
                if new_password != confirm_new_password:
                    flash("New passwords do not match.", "error")
                elif user.check_password(current_password):
                    user.password_hash = generate_password_hash(new_password)
                    user.save()
                    flash("Password updated successfully.", "success")
                else:
                    flash("Incorrect current password.", "error")
            elif "delete_uploads" in request.form:
                password = request.form["password"]
                if user.check_password(password):
                    uploads = db_handler.execute(
                        "SELECT filename FROM uploads WHERE owner_identifier = ?",
                        (user.account_identifier,),
                    )
                    for upload in uploads:
                        file_path = os.path.join(UPLOAD_FOLDER, upload[0])
                        if os.path.exists(file_path):
                            os.remove(file_path)
                    db_handler.execute(
                        "DELETE FROM uploads WHERE owner_identifier = ?",
                        (user.account_identifier,),
                    )
                    flash("All uploads deleted successfully.", "success")
                else:
                    flash("Incorrect password.", "error")
            elif "request_data" in request.form:
                password = request.form["password"]
                if user.check_password(password):
                    flash(
                        "Your data request has been received. You will receive an email with your data within 30 working days.",
                        "success",
                    )
                    flash(
                        "NOT IMPLEMENTED",
                        "success",
                    )
                else:
                    flash("Incorrect password.", "error")
            return redirect(url_for("dashboard.settings"))
        except ValueError as e:
            flash(str(e), "error")
        return redirect(url_for("dashboard.settings"))

    return render_template(
        "dashboard_settings.html",
        active_page="settings",
        is_admin=user.is_admin,
        pagetitle=build_title("Settings"),
        username=user.username,
        email=user.email,
        user_secret=user.account_identifier,
        sharex_key=user.secret_key,
        sharex_address=url_for("upload.sharex", _external=True),
        sharex_config=f"""{{
    "Version": "16.1.0",
    "Name": "Rystal Files",
    "DestinationType": "ImageUploader, FileUploader",
    "RequestMethod": "POST",
    "RequestURL": "{url_for("upload.sharex", _external=True)}",
    "Body": "MultipartFormData",
    "Arguments": {{
        "secret_key": "{user.secret_key}"
    }},
    "FileFormName": "file",
    "URL": "{{json:url}}"
}}""",
    )


@dashboard_bp.route("/upload")
@login_required
def upload():
    user = current_user
    return render_template(
        "dashboard_upload.html",
        is_admin=user.is_admin,
        active_page="upload",
        pagetitle=build_title("Upload"),
    )


@dashboard_bp.route("/files", methods=["GET"])
@login_required
def files():
    user = current_user
    page = request.args.get("page", 1, type=int)
    per_page = 25
    offset = (page - 1) * per_page

    sort_by = request.args.get("sort_by", "upload_time")
    sort_order = request.args.get("sort_order", "desc")
    search = request.args.get("search", "")

    valid_sort_by = ["filename", "upload_time", "views", "size"]
    valid_sort_order = ["asc", "desc"]

    if sort_by not in valid_sort_by:
        sort_by = "upload_time"
    if sort_order not in valid_sort_order:
        sort_order = "desc"

    if sort_by == "filename":
        sort_by = "original_name"

    search_query = f"%{search}%"

    total_files = db_handler.execute(
        "SELECT COUNT(*) FROM uploads WHERE owner_identifier = ? AND original_name LIKE ?",
        (user.account_identifier, search_query),
    )[0][0]

    uploads = db_handler.execute(
        f"SELECT original_name, filename, upload_time, size, views, password_hash FROM uploads WHERE owner_identifier = ? AND original_name LIKE ? ORDER BY {sort_by} {sort_order} LIMIT ? OFFSET ?",
        (user.account_identifier, search_query, per_page, offset),
    )

    formatted_uploads = []
    for upload in uploads:
        upload_time = datetime.datetime.strptime(upload[2], "%Y-%m-%d %H:%M:%S.%f")

routes/invite_routes.py
import re

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_user

from models.invite import Invite
from models.user import create_account

invite_bp = Blueprint("invite", __name__)


def validate_password(password):
    if len(password) < 8:
        return False
    if not re.search(r"[A-Za-z]", password):
        return False
    if not re.search(r"\d", password):
        return False
    return True


@invite_bp.route("/<code>", methods=["GET", "POST"])
def register(code):
    invite = Invite.get_by_code(code)
    if not invite or invite.used:
        flash("Invalid or expired invite code.")
        return redirect(url_for("auth.login"))

    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        if not validate_password(password):
            flash(
                "Password must be at least 8 characters long and contain at least one number and one alphabet."
            )
            return render_template("register_view.html", code=code)
        try:
            user = create_account(username, password)
            invite.mark_as_used()
            login_user(user)
            flash("Account created successfully.")
            return redirect(url_for("dashboard.dashboard"))
        except ValueError as e:
            flash(str(e))

    return render_template("register_view.html", code=code)

routes/upload_routes.py
import datetime
import os
import random
import string

from flask import Blueprint, jsonify, request, url_for
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash

from constant import BASE_DIR
from database import db_handler
from models.user import User

upload_bp = Blueprint("upload", __name__)
storage_folder = os.path.join(BASE_DIR, "uploads")


def secure_string(length):
    characters = string.ascii_letters + string.digits
    return "".join(random.choice(characters) for _ in range(length))


def secure_filename(filename):
    filename = filename.strip()
    if "." in filename:
        name = secure_string(12)
        extension = filename.rsplit(".", 1)[1].lower()
        return f"{name}.{extension}"
    return filename


@upload_bp.route("/sharex", methods=["POST"])
def sharex():
    if "file" not in request.files:
        return jsonify({"error": "No file part"}), 400
    file = request.files["file"]
    if file.filename == "":
        return jsonify({"error": "No selected file"}), 400

    secret_key = request.form.get("secret_key")
    user = User.get_by_secret_key(secret_key)
    if not user:
        return jsonify({"error": "Invalid secret key"}), 403
    filename = secure_filename(file.filename)
    file.save(os.path.join(storage_folder, filename))
    file_size = os.path.getsize(os.path.join(storage_folder, filename))
    upload_time = datetime.datetime.now()
    db_handler.execute(
        "INSERT INTO uploads (original_name, filename, views, size, owner_identifier, upload_time) VALUES (?, ?, ?, ?, ?, ?)",
        (
            file.filename,
            filename,
            0,
            file_size,
            user.account_identifier,
            upload_time,
        ),
    )
    return (
        jsonify({"url": url_for("view.view", filename=filename, _external=True)}),
        201,
    )


@upload_bp.route("/dashboard", methods=["POST"])
@login_required
def dashboard():
    if "file" not in request.files:
        return jsonify({"error": "No file part"}), 400
    file = request.files["file"]
    if file.filename == "":
        return jsonify({"error": "No selected file"}), 400

    user = current_user
    filename = secure_filename(file.filename)
    file.save(os.path.join(storage_folder, filename))
    file_size = os.path.getsize(os.path.join(storage_folder, filename))
    upload_time = datetime.datetime.now()
    password = request.form.get("password")
    password_hash = generate_password_hash(password) if password else None
    db_handler.execute(
        "INSERT INTO uploads (original_name, filename, views, size, owner_identifier, upload_time, password_hash) VALUES (?, ?, ?, ?, ?, ?, ?)",
        (
            file.filename,
            filename,
            0,
            file_size,
            user.account_identifier,
            upload_time,
            password_hash,
        ),
    )

    return (
        jsonify({"url": url_for("view.view", filename=filename, _external=True)}),
        201,
    )

templates/audio_view.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{{ pagetitle }}</title>

		<meta property="og:title" content="{{ filename }}" />
		<meta
			property="og:url"
			content="https://files.rystal.space/storage/{{ filename }}"
		/>
		<meta property="og:type" content="audio.other" />
		<meta
			property="og:audio"
			content="https://files.rystal.space/storage/{{ filename }}"
		/>
		<meta property="og:audio:type" content="audio/mpeg" />

		<link rel="stylesheet" href="https://cdn.plyr.io/3.6.8/plyr.css" />
		<link rel="icon" href="/static/favicon.png" type="image/png" />
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='styles.css') }}"
		/>
	</head>
	<body>
		<div class="audio-container">
			<audio id="player" class="plyr" controls>
				<source src="/storage/{{ filename }}" type="audio/mp3" />
				Your browser does not support the audio tag.
			</audio>
		</div>

		<script src="https://cdn.plyr.io/3.6.8/plyr.polyfilled.js"></script>
		<script>
			document.addEventListener("DOMContentLoaded", () => {
				const player = new Plyr("#player");
			});
		</script>

		<a href="/storage/{{ filename }}" class="general-button" download
			>Download</a
		>
	</body>
</html>

templates/dashboard_admin.html
{% extends "dashboard_base.html" %} {% block title %}Administration{% endblock
%} {% block content %}
<header class="header-bar">
	<h1>Administration</h1>
</header>
<div class="admin-container">
	<div class="section">
		<header class="section-title">
			<h2>All Users</h2>
		</header>
		<div class="file-list-container">
			<table class="file-list-table">
				<thead>
					<tr>
						<th class="file-list-table-title">Username</th>
						<th class="file-list-table-title">Email</th>
						<th class="file-list-table-title">Admin</th>
						<th class="file-list-table-title">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for user in users %}
					<tr>
						<td class="file-list-table-item">{{ user.username }}</td>
						<td class="file-list-table-item">{{ user.email }}</td>
						<td class="file-list-table-item">{{ user.is_admin }}</td>
						<td class="actions">
							<form method="POST" style="display: inline">
								<button
									type="button"
									class="other-btn"
									data-user-id="{{ user.id }}"
									data-username="{{ user.username }}"
									data-email="{{ user.email }}"
									data-is-admin="{{ user.is_admin }}"
								>
									<i class="fa-solid fa-edit" style="color: #007bff"></i>
								</button>
								<button
									type="submit"
									name="delete_user"
									value="{{ user.id }}"
									class="delete-btn"
								>
									<i class="fa-solid fa-trash" style="color: #d01616"></i>
								</button>
							</form>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

	<div class="section">
		<header class="section-title">
			<h2>Create Invite Link</h2>
		</header>
		<form method="POST">
			<button type="submit" name="create_invite" class="general-button">
				Create Invite Link
			</button>
		</form>
	</div>

	<div class="section">
		<header class="section-title">
			<h2>All Invites</h2>
		</header>
		<div class="file-list-container">
			<table class="file-list-table">
				<thead>
					<tr>
						<th class="file-list-table-title">Code</th>
						<th class="file-list-table-title">Link</th>
						<th class="file-list-table-title">Used</th>
						<th class="file-list-table-title">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for invite in invites %}
					<tr>
						<td class="file-list-table-item">{{ invite.code }}</td>
						<td class="file-list-table-item">
							{{ url_for('invite.register', code=invite.code, _external=True) }}
						</td>
						<td class="file-list-table-item">{{ invite.used }}</td>
						<td class="actions">
							<form method="POST" style="display: inline">
								<button
									type="submit"
									name="delete_invite"
									value="{{ invite.code }}"
									class="delete-btn"
								>
									<i class="fa-solid fa-trash" style="color: #d01616"></i>
								</button>
							</form>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

<div id="editUserModal" class="modal">
	<div class="modal-content">
		<span class="close">&times;</span>
		<h2>Edit User</h2>
		<form method="POST">
			<input type="hidden" name="edit_user" id="edit_user_id" />
			<div class="form-group">
				<label for="new_username">Username</label>
				<input type="text" id="new_username" name="new_username" required />
			</div>
			<div class="form-group">
				<label for="new_email">Email</label>
				<input type="email" id="new_email" name="new_email" required />
			</div>
			<div class="form-group">
				<label for="is_admin">Admin</label>
				<input type="checkbox" id="is_admin" name="is_admin" />
			</div>
			<button type="submit" class="general-button">Save Changes</button>
		</form>
	</div>
</div>

<script>
	document.addEventListener("DOMContentLoaded", function () {
		const editButtons = document.querySelectorAll(".other-btn");
		const modal = document.getElementById("editUserModal");
		const closeModal = document.querySelector(".close");

		editButtons.forEach((button) => {
			button.addEventListener("click", function () {
				const userId = this.dataset.userId;
				const username = this.dataset.username;
				const email = this.dataset.email;
				const isAdmin = this.dataset.isAdmin === "True";

				document.getElementById("edit_user_id").value = userId;
				document.getElementById("new_username").value = username;
				document.getElementById("new_email").value = email;
				document.getElementById("is_admin").checked = isAdmin;

				modal.style.display = "block";
			});
		});

		closeModal.addEventListener("click", function () {
			modal.style.display = "none";
		});

		window.addEventListener("click", function (event) {
			if (event.target === modal) {
				modal.style.display = "none";
			}
		});
	});
</script>
{% endblock %}

templates/dashboard_base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title %}Dashboard{% endblock %}</title>
		<link rel="icon" href="/static/favicon.png" type="image/png" />
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
		/>
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='styles.css') }}"
		/>
		<link
			rel="stylesheet"
			href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/dark.min.css"
		/>
		<link rel="stylesheet" href="/static/code.css" />
	</head>
	<body>
		<div class="dashboard-container">
			<aside class="sidebar">
				<nav>
					<img
						src="/static/assets/logo-banner.webp"
						alt="Logo"
						class="dashboard-logo"
					/>
					<ul>
						<li>
							<a
								href="/dashboard"
								class="{% if active_page == 'home' %}active{% endif %}"
								>Home</a
							>
						</li>
						<li>
							<a
								href="/dashboard/files"
								class="{% if active_page == 'files' %}active{% endif %}"
								>Files</a
							>
						</li>
						<li>
							<a
								href="/dashboard/upload"
								class="{% if active_page == 'upload' %}active{% endif %}"
								>Upload</a
							>
						</li>
						<li>
							<a
								href="/dashboard/settings"
								class="{% if active_page == 'settings' %}active{% endif %}"
								>Settings</a
							>
						</li>
						{% if is_admin %}
						<li>
							<a
								href="/dashboard/admin"
								class="{% if active_page == 'admin' %}active{% endif %}"
								>Administration</a
							>
						</li>
						{% endif %}
					</ul>
				</nav>
				<div class="sidebar-version">
					<small>Version: {{ version }}</small>
				</div>
			</aside>
			<div class="main-content">
				{% block content %}{% endblock %}
				<footer class="dashboard-footer">
					<p>
						<small
							>Copyright © 2024 <a href="https://rystal.net">Rystal</a>. All
							rights reserved.</small
						>
					</p>
				</footer>
			</div>
		</div>
		<div id="notification-frame" class="notification-frame"></div>
	</body>
	<script>
		function showNotification(message, type) {
		    const notificationFrame = document.getElementById('notification-frame');
		    notificationFrame.textContent = message;
		    notificationFrame.className = `notification-frame show ${type}`;
		    setTimeout(() => {
		        notificationFrame.className = 'notification-frame';
		    }, 3000);
		}

		document.addEventListener('DOMContentLoaded', () => {
		    const messages = {{ get_flashed_messages(with_categories=true) | tojson | safe }};
		    messages.forEach(([category, message]) => {
		        showNotification(message, category);
		    });

		    const notification = {{ session.get('notification') | tojson | safe }};
		    if (notification) {
		        showNotification(notification.message, notification.type);
		        fetch("{{ url_for('dashboard.clear_notification') }}");
		    }
		});
	</script>
</html>

templates/dashboard_files.html
{% extends "dashboard_base.html" %} {% block title %}{{ pagetitle }}{% endblock %} {% block content %}
<header class="header-bar">
    <h1>Uploaded Files</h1>
</header>
<div class="file-list">
    <div class="file-list-container">
        <form method="GET" class="sort-form">
            <label for="search">Search:</label>
            <input class="filename-search" type="text" name="search" id="search" value="{{ search }}" placeholder="Search by filename">
            <label for="sort_by">Sort by:</label>
            <select name="sort_by" id="sort_by">
                <option value="filename" {% if sort_by == 'filename' %}selected{% endif %}>Filename</option>
                <option value="upload_time" {% if sort_by == 'upload_time' %}selected{% endif %}>Date Uploaded</option>
                <option value="views" {% if sort_by == 'views' %}selected{% endif %}>Views</option>
                <option value="size" {% if sort_by == 'size' %}selected{% endif %}>Size</option>
            </select>
            <select name="sort_order" id="sort_order">
                <option value="asc" {% if sort_order == 'asc' %}selected{% endif %}>Ascending</option>
                <option value="desc" {% if sort_order == 'desc' %}selected{% endif %}>Descending</option>
            </select>
            <button type="submit" class="dark-button">Sort</button>
        </form>
        <table class="file-list-table">
            <thead>
                <tr>
                    <th class="file-list-table-title">Filename</th>
                    <th class="file-list-table-title">Date Uploaded</th>
                    <th class="file-list-table-title">Views</th>
                    <th class="file-list-table-title">Size</th>
                    <th class="file-list-table-title">Protected</th>
                    <th class="file-list-table-title">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for upload in uploads %}
                <tr>
                    <td class="file-list-table-item">{{ upload[0] }}</td>
                    <td class="file-list-table-item">{{ upload[2] }}</td>
                    <td class="file-list-table-item">{{ upload[4] }}</td>
                    <td class="file-list-table-item" data-size="{{ upload[3] }}"></td>
                    <td class="file-list-table-item">{{ upload[5] }}</td>
                    <td class="actions">
                        <a href="/view/{{ upload[1] }}" style="text-decoration: none;">
                            <i class="fa-solid fa-eye" style="color: #ffffff"></i>
                        </a>
                        <button class="delete-btn" data-filename="{{ upload[1] }}">
                            <i class="fa-solid fa-trash" style="color: #d01616"></i>
                        </button>
                        <button class="other-btn" data-filename="{{ upload[1] }}">
                            <i class="fa-solid fa-lock" style="color: #007bff"></i>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination">
        {% if page > 1 %}
        <a href="{{ url_for('dashboard.files', page=page-1, sort_by=sort_by, sort_order=sort_order, search=search) }}" class="general-button">Previous</a>
        {% endif %}
        {% if page < total_pages %}
        <a href="{{ url_for('dashboard.files', page=page+1, sort_by=sort_by, sort_order=sort_order, search=search) }}" class="general-button">Next</a>
        {% endif %}
    </div>
</div>

<div id="setPasswordModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h2>Set Password for File</h2>
        <form id="set-password-form" method="POST">
            <input type="hidden" name="filename" id="set_password_filename">
            <div class="dashboard-item-container">
                <label class="dashboard-item-label" for="new_password">Password</label>
            </div>
            <div class="dashboard-item-container">
                <div class="form-group">
                    <input class="dashboard-item-input" type="password" id="new_password" name="new_password">
                </div>
            </div>
            <div class="dashboard-item-container">
                <button type="submit" class="dashboard-item-button">Set Password</button>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const setPasswordButtons = document.querySelectorAll(".other-btn");
        const modal = document.getElementById("setPasswordModal");
        const closeModal = document.querySelector(".close");

        setPasswordButtons.forEach(button => {
            button.addEventListener("click", function () {
                const filename = this.dataset.filename;
                document.getElementById("set_password_filename").value = filename;
                modal.style.display = "block";
            });
        });

        closeModal.addEventListener("click", function () {
            modal.style.display = "none";
        });

        window.addEventListener("click", function (event) {
            if (event.target === modal) {
                modal.style.display = "none";
            }
        });

        document.getElementById("set-password-form").addEventListener("submit", function (event) {
            event.preventDefault();
            const formData = new FormData(this);
            fetch("{{ url_for('dashboard.set_password') }}", {
                method: "POST",
                body: formData,
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    showNotification("Password set successfully", "success");
                    modal.style.display = "none";
                } else {
                    showNotification("Error: " + data.error, "error");
                }
            })
            .catch(error => {
                console.error("Error:", error);
                showNotification("An error occurred while setting the password", "error");
            });
        });
    });

    document.addEventListener("DOMContentLoaded", function () {
        const sizeCells = document.querySelectorAll('.file-list-table-item[data-size]');
        sizeCells.forEach(cell => {
            const size = parseInt(cell.getAttribute('data-size'), 10);
            cell.textContent = formatSize(size);
        });
    });

    function formatSize(size) {
        const units = ['B', 'KB', 'MB', 'GB', 'TB'];
        let unitIndex = 0;
        while (size >= 1024 && unitIndex < units.length - 1) {
            size /= 1024;
            unitIndex++;
        }
        return `${size.toFixed(2)} ${units[unitIndex]}`;
    }
</script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const deleteButtons = document.querySelectorAll(".delete-btn");
        deleteButtons.forEach(button => {
            button.addEventListener("click", function () {
                const filename = this.dataset.filename;
                if (confirm("Are you sure you want to delete this file?")) {
                    const formData = new FormData();
                    formData.append("filename", filename);
                    fetch("{{ url_for('dashboard.delete_file') }}", {
                        method: "POST",
                        body: formData,
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                location.reload();
                            } else {
                                showNotification("Error: " + data.error, "error");
                            }
                        })
                        .catch(error => {
                            console.error("Error:", error);
                            showNotification("An error occurred while deleting the file", "error");
                        });
                }
            });
        });
    });
</script>
{% endblock %}